name: "ryansingman/deploy-bot"
description: "Deployment merge handler."
author: "Ryan Singman @ Cleanlab"
inputs:
  source:
    description: source branch to create merge from
    required: false
    default: "staging"
  target:
    description: target branch to merge into
    required: false
    default: "main"
runs:
  using: composite
  steps:
    # checkout <source> branch of repo
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.source }}

    # name deployment branch
    - run: |
        echo "DEPLOYMENT_BRANCH=deployment/$(date +'%m-%d-%Y')" >> $GITHUB_ENV
      shell: bash

    # create deployment branch off of source branch
    # named deployment_{date}
    - run: |
        git checkout -b ${{ env.DEPLOYMENT_BRANCH }} \
        && git push --set-upstream origin ${{ env.DEPLOYMENT_BRANCH }}
      shell: bash

    # create PR to target branch from deployment branch

    # tag all contributors on PR branch
    # > how to do? diff <deployment> and <target> and get usernames?
